# Data Cleaning Project: Dirty Cafe Sales

## 1. Import Libraries
We import pandas for data manipulation and numpy for missing values.

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

## 2. Load Dataset

In [2]:
df = pd.read_csv('dirty_cafe_sales.csv')
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

3. Explore the Dataset

In [3]:
df.info()
df.shape
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

## 4. Check Missing Values and Duplicates

In [4]:
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

## 5. Inspect Unique Values
This helps identify inconsistent entries like UNKNOWN, ERROR or N/A.

In [5]:
for col in df.columns:
    print(f'\n{col}')
    print(df[col].unique())

Transaction ID
['TXN_1961373' 'TXN_4977031' 'TXN_4271903' ... 'TXN_5255387' 'TXN_7695629'
 'TXN_6170729']

Item
['Coffee' 'Cake' 'Cookie' 'Salad' 'Smoothie' 'UNKNOWN' 'Sandwich' nan
 'ERROR' 'Juice' 'Tea']

Quantity
['2' '4' '5' '3' '1' 'ERROR' 'UNKNOWN' nan]

Price Per Unit
['2.0' '3.0' '1.0' '5.0' '4.0' '1.5' nan 'ERROR' 'UNKNOWN']

Total Spent
['4.0' '12.0' 'ERROR' '10.0' '20.0' '9.0' '16.0' '15.0' '25.0' '8.0' '5.0'
 '3.0' '6.0' nan 'UNKNOWN' '2.0' '1.0' '7.5' '4.5' '1.5']

Payment Method
['Credit Card' 'Cash' 'UNKNOWN' 'Digital Wallet' 'ERROR' nan]

Location
['Takeaway' 'In-store' 'UNKNOWN' nan 'ERROR']

Transaction Date
['2023-09-08' '2023-05-16' '2023-07-19' '2023-04-27' '2023-06-11'
 '2023-03-31' '2023-10-06' '2023-10-28' '2023-07-28' '2023-12-31'
 '2023-11-07' 'ERROR' '2023-05-03' '2023-06-01' '2023-03-21' '2023-11-15'
 '2023-06-10' '2023-02-24' '2023-03-25' '2023-01-15' '2023-04-04'
 '2023-03-30' '2023-12-01' '2023-09-18' '2023-06-03' '2023-12-13'
 '2023-04-20' '2023-04-10' '2023-03-11' '2023-06-02' '2023-11-06'
 '2023-08-15' '2023-10-09' '2023-05-28' '2023-07-17' '2023-04-29'
 '2023-06-08' '2023-06-29' '2023-04-17' '2023-12-22' '2023-01-10'
 '2023-10-02' '2023-02-23' '2023-03-22' '2023-11-03' '2023-03-02'
 '2023-06-26' '2023-05-02' '2023-09-05' '2023-01-08' '2023-03-15'
 '2023-11-25' '2023-12-05' '2023-03-19' '2023-06-27' '2023-04-19'
 '2023-10-07' '2023-09-30' '2023-05-27' '2023-11-18' '2023-10-20'
 '2023-10-03' '2023-10-27' '2023-04-06' '2023-01-31' '2023-12-08'
 '2023-06-19' '2023-12-14' '2023-07-16' '2023-02-22' nan '2023-06-15'
 '2023-12-09' '2023-04-18' '2023-10-29' '2023-04-30' '2023-04-02'
 '2023-05-24' '2023-03-12' '2023-08-16' '2023-09-10' '2023-03-07'
 '2023-08-07' '2023-08-20' '2023-04-15' '2023-07-25' '2023-10-30'
 '2023-12-15' '2023-02-25' '2023-04-03' '2023-10-08' '2023-12-28'
 '2023-08-30' '2023-02-03' '2023-09-12' '2023-05-04' '2023-02-21'
 'UNKNOWN' '2023-03-16' '2023-02-06' '2023-03-29' '2023-06-18'
 '2023-09-23' '2023-01-14' '2023-09-14' '2023-09-16' '2023-04-08'
 '2023-12-19' '2023-07-14' '2023-12-12' '2023-01-05' '2023-01-23'
 '2023-02-20' '2023-12-06' '2023-05-31' '2023-08-11' '2023-09-03'
 '2023-07-11' '2023-06-06' '2023-01-18' '2023-03-23' '2023-01-04'
 '2023-06-23' '2023-08-03' '2023-07-12' '2023-11-02' '2023-07-31'
 '2023-09-19' '2023-02-09' '2023-09-04' '2023-05-21' '2023-07-02'
 '2023-07-10' '2023-11-21' '2023-12-02' '2023-03-13' '2023-08-12'
 '2023-02-16' '2023-04-11' '2023-03-26' '2023-11-01' '2023-07-22'
 '2023-07-26' '2023-02-28' '2023-01-27' '2023-01-19' '2023-04-07'
 '2023-03-20' '2023-12-27' '2023-10-26' '2023-02-18' '2023-05-15'
 '2023-12-10' '2023-04-21' '2023-02-04' '2023-11-12' '2023-08-05'
 '2023-05-10' '2023-07-15' '2023-01-11' '2023-10-01' '2023-04-26'
 '2023-08-25' '2023-03-01' '2023-11-13' '2023-07-09' '2023-05-13'
 '2023-05-18' '2023-01-17' '2023-09-22' '2023-08-22' '2023-07-27'
 '2023-12-30' '2023-12-21' '2023-09-28' '2023-11-16' '2023-04-14'
 '2023-01-03' '2023-01-12' '2023-08-31' '2023-07-07' '2023-09-15'
 '2023-10-21' '2023-09-02' '2023-08-19' '2023-01-06' '2023-10-13'
 '2023-05-29' '2023-05-22' '2023-11-23' '2023-10-15' '2023-11-14'
 '2023-11-26' '2023-12-17' '2023-05-09' '2023-10-22' '2023-06-30'
 '2023-04-25' '2023-02-19' '2023-12-11' '2023-10-12' '2023-07-04'
 '2023-01-28' '2023-10-04' '2023-02-26' '2023-10-11' '2023-02-14'
 '2023-04-28' '2023-09-06' '2023-04-23' '2023-01-22' '2023-03-10'
 '2023-01-09' '2023-12-03' '2023-08-06' '2023-12-29' '2023-02-15'
 '2023-05-25' '2023-10-31' '2023-02-27' '2023-03-03' '2023-09-27'
 '2023-08-18' '2023-12-16' '2023-06-07' '2023-05-12' '2023-07-06'
 '2023-06-20' '2023-08-09' '2023-05-14' '2023-07-18' '2023-10-10'
 '2023-02-02' '2023-08-14' '2023-09-26' '2023-01-13' '2023-10-16'
 '2023-11-17' '2023-12-20' '2023-12-04' '2023-02-08' '2023-09-11'
 '2023-02-01' '2023-02-12' '2023-03-14' '2023-09-29' '2023-04-22'
 '2023-06-13' '2023-12-24' '2023-03-28' '2023-03-06' '2023-02-11'
 '2023-01-30' '2023-04-09' '2023-04-16' '2023-12-23' '2023-03-05'
 '2023-03-24' '2023-07-23' '2023-07-29' '2023-06-05' '2023-10-19'
 '2023-01-07' '2023-11-29' '2023-07-05' '2023-07-20' '2023-05-07'
 '2023-08-10' '2023-10-24' '2023-08-13' '2023-08-28' '2023-06-21'
 '2023-11-10' '2023-10-18' '2023-05-19' '2023-11-09' '2023-06-24'
 '2023-05-11' '2023-12-07' '2023-09-01' '2023-09-25' '2023-06-22'
 '2023-05-30' '2023-04-24' '2023-09-20' '2023-02-07' '2023-05-05'
 '2023-02-10' '2023-11-24' '2023-10-25' '2023-10-05' '2023-07-21'
 '2023-07-08' '2023-03-17' '2023-10-14' '2023-06-28' '2023-09-09'
 '2023-08-21' '2023-07-01' '2023-06-14' '2023-03-09' '2023-11-08'
 '2023-12-26' '2023-09-13' '2023-05-23' '2023-08-24' '2023-04-01'
 '2023-06-09' '2023-08-23' '2023-08-08' '2023-08-27' '2023-05-26'
 '2023-06-16' '2023-12-25' '2023-01-25' '2023-10-23' '2023-05-06'
 '2023-01-29' '2023-08-29' '2023-01-01' '2023-07-24' '2023-04-12'
 '2023-12-18' '2023-09-21' '2023-05-01' '2023-02-05' '2023-01-24'
 '2023-01-02' '2023-06-12' '2023-01-16' '2023-10-17' '2023-03-04'
 '2023-06-17' '2023-03-18' '2023-08-26' '2023-05-17' '2023-11-22'
 '2023-08-17' '2023-11-19' '2023-11-27' '2023-06-04' '2023-09-17'
 '2023-11-04' '2023-11-28' '2023-06-25' '2023-04-13' '2023-01-26'
 '2023-08-04' '2023-05-08' '2023-11-20' '2023-07-13' '2023-09-24'
 '2023-01-21' '2023-03-08' '2023-09-07' '2023-11-30' '2023-08-02'
 '2023-04-05' '2023-08-01' '2023-01-20' '2023-11-11' '2023-02-13'
 '2023-07-30' '2023-02-17' '2023-05-20' '2023-11-05' '2023-03-27'
 '2023-07-03']

## 6. Replace Common Invalid Values

Many datasets use placeholders instead of true missing values.
We replace them with `np.nan` so pandas recognizes them as missing.

In [6]:
invalid_values = ['UNKNOWN','Unknown','ERROR','Error','N/A','NULL','null','?','']
df.replace(invalid_values, np.nan, inplace=True)
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

## 7. Convert Data Types

In [ ]:
for c in df.columns:
    print(c, '=', df[c].dtype)

numeric = ['Quantity', 'Price Per Unit', 'Total Spent',]
for c in numeric:
    df[c] = pd.to_numeric(df[c])

df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

Transaction ID = object
Item = object
Quantity = float64
Price Per Unit = float64
Total Spent = float64
Payment Method = object
Location = object
Transaction Date = datetime64[ns]
Transaction ID = object
Item = object
Quantity = float64
Price Per Unit = float64
Total Spent = float64
Payment Method = object
Location = object
Transaction Date = datetime64[ns]

## 8. Handle Missing Values

In [32]:
for col in df.columns:
    if df[col].dtype == 'object':
        if df[col].isna().any():
            df[col].fillna(df[col].mode()[0], inplace=True)
    else:
        if df[col].isna().any():
            df[col].fillna(df[col].median(), inplace=True)

df.isnull().sum()

C:\Users\Mumba Mumba\AppData\Local\Temp\ipykernel_18072\3761605338.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

## 9. Remove Duplicates

In [33]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

## 10. Final Validation

In [34]:
df.info()
df.describe(include='all')
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              10000 non-null  object
 2   Quantity          10000 non-null  float64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       10000 non-null  float64
 5   Payment Method    10000 non-null  object
 6   Location          10000 non-null  object
 7   Transaction Date  10000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 625.1+ KB

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

## 11. Save Clean Dataset

In [35]:
df.to_csv('cleaned_dirty_cafe_sales.csv', index=False)
print('Dataset saved successfully.')

Dataset saved successfully.

In [36]:
df.describe()

,Quantity,Price Per Unit,Total Spent,Transaction Date
count,10000.000000,10000.00000,10000.00000,10000
mean,3.027100,2.95265,8.87795,2023-07-01 23:03:15.840000256
min,1.000000,1.00000,1.00000,2023-01-01 00:00:00
25%,2.000000,2.00000,4.00000,2023-04-06 00:00:00
50%,3.000000,3.00000,8.00000,2023-07-02 00:00:00
75%,4.000000,4.00000,12.00000,2023-09-27 00:00:00
max,5.000000,5.00000,25.00000,2023-12-31 00:00:00
std,1.384614,1.24396,5.86059,NaN